# Generated by Django 6.0.4 on 2026-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='directorprofile',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_director_per_school'),
        ),
    ]
