# Generated by Django 6.0.4 on 2026-04-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_unique_academic_year_name_per_school'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectcoefficient',
            name='unique_subject_coefficient_per_level',
        ),
        migrations.AddField(
            model_name='subjectcoefficient',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_coefficients', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='absences/proofs/'),
        ),
        migrations.AddConstraint(
            model_name='subjectcoefficient',
            constraint=models.UniqueConstraint(fields=('subject', 'level', 'academic_year'), name='unique_subject_coefficient_per_level_year'),
        ),
    ]
