# Generated by Django 6.0.4 on 2026-04-26 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classchangerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_class_changes', to='accounts.directorprofile'),
        ),
        migrations.AddField(
            model_name='classchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_change_requests', to='accounts.secretaryprofile'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.level'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classchangerequest',
            name='from_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_changes_from', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classchangerequest',
            name='to_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_changes_to', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.parentprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classchangerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_change_requests', to='academics.student'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='accounts.teacherprofile'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='unique_active_academic_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'level', 'name', 'academic_year'), name='unique_class_per_school_level_name_year'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'registration_number'), name='unique_registration_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'school_class', 'subject', 'academic_year'), name='unique_teaching_assignment'),
        ),
    ]
